import { WeightedGraph } from "./classes/weighted-graph.js";
import { WeightedGraphOOP } from "./classes/weighted-graph-oop.js";

console.log("WeightedGraph");
const graph = new WeightedGraph();
graph.addNode("A");
graph.addNode("B");
graph.addNode("C");
graph.addEdge("A", "B", 3);
graph.addEdge("A", "C", 2);
graph.print();
console.log("hasCycle", graph.hasCycle());
graph.addEdge("C", "A", 4);
console.log("hasCycle after adding edge C, A", graph.hasCycle());
console.log("\n");

console.log("WeightedGraphOOP");
const graph2 = new WeightedGraphOOP();
graph2.addNode("A");
graph2.addNode("B");
graph2.addNode("C");
graph2.addEdge("A", "B", 3);
graph2.addEdge("B", "C", 2);
graph2.addEdge("A", "C", 10);
graph2.print();
console.log("shortest Path", graph2.getShortestPath("A", "C"));
console.log("hasCycle", graph2.hasCycle());
graph2.addEdge("C", "A", 4);
console.log("hasCycle after adding edge C, A", graph2.hasCycle());

console.log("\n");
console.log("WeightedGraphOOP - getMinimumSpanningTree - Prim's altorithm");
const graph3 = new WeightedGraphOOP();
graph3.addNode("A");
graph3.addNode("B");
graph3.addNode("C");
graph3.addNode("D");
graph3.addEdge("A", "B", 3);
graph3.addEdge("B", "D", 4);
graph3.addEdge("C", "D", 5);
graph3.addEdge("A", "C", 1);
graph3.addEdge("B", "C", 2);
const tree = graph3.getMinimumSpanningTree();
tree.print();
