import { StackQueue } from "./classes/index.js";

const stackQueue = new StackQueue(5);
console.log("stackQueue.isFull", stackQueue.isFull);
console.log("stackQueue.isEmpty", stackQueue.isEmpty);
stackQueue.enqueue(10);
stackQueue.enqueue(20);
stackQueue.enqueue(30);
console.log("stackQueue.items", stackQueue.items);
console.log("stackQueue.peek()", stackQueue.peek());
stackQueue.enqueue(40);
stackQueue.enqueue(50);
console.log("stackQueue.peek()", stackQueue.peek());
console.log("stackQueue.isFull", stackQueue.isFull);
console.log("stackQueue.isEmpty", stackQueue.isEmpty);
stackQueue.enqueue(60);
console.log("stackQueue.items", stackQueue.items);
console.log("stackQueue.dequeue()", stackQueue.dequeue());
console.log("stackQueue.items", stackQueue.items);
stackQueue.enqueue(60);
console.log("stackQueue.items", stackQueue.items);
console.log("stackQueue.dequeue()", stackQueue.dequeue());
console.log("stackQueue.dequeue()", stackQueue.dequeue());
console.log("stackQueue.items", stackQueue.items);
console.log("stackQueue.dequeue()", stackQueue.dequeue());
console.log("stackQueue.dequeue()", stackQueue.dequeue());
console.log("stackQueue.items", stackQueue.items);
console.log("stackQueue.dequeue()", stackQueue.dequeue());
console.log("stackQueue.items", stackQueue.items);
console.log("stackQueue.isFull", stackQueue.isFull);
console.log("stackQueue.isEmpty", stackQueue.isEmpty);
